# Generated by Django 3.0.8 on 2020-07-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
