# Generated by Django 3.0.8 on 2020-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200712_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='New'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False, verbose_name='Top Selling'),
        ),
    ]
