# Generated by Django 3.0.8 on 2020-07-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_with_discount',
        ),
    ]
